import { StyleSheet } from 'react-native';
import { spacing, fontSize, borderRadius } from '@/shared/theme/spacing';

export const createStyles = (c: ReturnType<typeof import('@/shared/hooks/useTheme').useTheme>) =>
  StyleSheet.create({
    container: { flex: 1 },
    scrollContent: { paddingBottom: spacing.xxxl },
    avatarSection: { alignItems: 'center', paddingVertical: spacing.xl },
    input: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: borderRadius.md,
      padding: spacing.md,
      fontSize: fontSize.md,
      color: c.text,
    },
    textarea: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: borderRadius.md,
      padding: spacing.md,
      fontSize: fontSize.md,
      color: c.text,
      minHeight: 80,
      textAlignVertical: 'top',
    },
    usernameRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
    usernamePrefix: { fontSize: fontSize.md, color: c.textTertiary },
    usernameCheck: { fontSize: fontSize.xs, marginTop: spacing.xs },
    usernameOk: { color: c.success },
    usernameBad: { color: c.error },
    saveBtn: {
      marginHorizontal: spacing.lg,
      backgroundColor: c.primary,
      paddingVertical: spacing.md,
      borderRadius: borderRadius.md,
      alignItems: 'center',
      marginTop: spacing.lg,
    },
    saveBtnText: { color: '#FFFFFF', fontSize: fontSize.md },
    statusPickerOverlay: { flex: 1, backgroundColor: c.overlay, justifyContent: 'flex-end' },
    statusPickerSheet: {
      backgroundColor: c.surface,
      borderTopLeftRadius: borderRadius.xl,
      borderTopRightRadius: borderRadius.xl,
      paddingBottom: spacing.xxxl,
      maxHeight: '60%',
    },
    statusPickerHandle: {
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: c.textTertiary,
      alignSelf: 'center',
      marginTop: spacing.md,
      marginBottom: spacing.md,
    },
    statusPickerTitle: { fontSize: fontSize.lg, color: c.text, textAlign: 'center', marginBottom: spacing.md },
    statusOption: { paddingVertical: spacing.md, paddingHorizontal: spacing.xxl },
    statusOptionText: { fontSize: fontSize.md, color: c.text },
    statusActive: { color: c.primary },
    customStatusInput: {
      marginHorizontal: spacing.xxl,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: borderRadius.md,
      padding: spacing.md,
      fontSize: fontSize.md,
      color: c.text,
      marginTop: spacing.sm,
    },
  });
